# Generated by Django 3.2.7 on 2024-01-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypertrek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekstate',
            name='uuid',
            field=models.UUIDField(editable=False),
        ),
    ]
